# Generated by Django 2.2.16 on 2022-07-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220729_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleGenre',
        ),
    ]
