# Generated by Django 2.2.16 on 2022-07-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220729_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleGenre',
            new_name='Genre_title',
        ),
    ]
