# Generated by Django 2.2.16 on 2022-07-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220729_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre_title',
            new_name='GenreTitle',
        ),
    ]
